-- MySQL Script generated by MySQL Workbench
-- Wed Sep  4 16:54:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Library` DEFAULT CHARACTER SET utf8 ;
USE `Library` ;

-- -----------------------------------------------------
-- Table `Library`.`D_Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Library`.`D_Users` ;

CREATE TABLE IF NOT EXISTS `Library`.`D_Users` (
  `Cd_id` INT NOT NULL AUTO_INCREMENT,
  `Li_FirstName` NVARCHAR(50) NOT NULL,
  `Li_LastName` NVARCHAR(50) NOT NULL,
  `Da_Birthday` DATE NULL DEFAULT NULL,
  `Li_Email` NVARCHAR(30) NULL DEFAULT NULL,
  `Cd_PreferredGenre` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`Cd_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library`.`D_Books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Library`.`D_Books` ;

CREATE TABLE IF NOT EXISTS `Library`.`D_Books` (
  `Cd_id` INT NOT NULL AUTO_INCREMENT,
  `Li_Title` NVARCHAR(50) NOT NULL,
  `Cd_Author` NVARCHAR(60) NULL DEFAULT NULL,
  `Cd_Genre` VARCHAR(25) NULL DEFAULT NULL,
  `Li_Height` INT NULL,
  `Cd_Publisher` NVARCHAR(45) NULL,
  PRIMARY KEY (`Cd_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library`.`F_Borroweds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Library`.`F_Borroweds` ;

CREATE TABLE IF NOT EXISTS `Library`.`F_Borroweds` (
  `Cd_id` INT NOT NULL AUTO_INCREMENT,
  `Cd_Books_id` INT NOT NULL,
  `Cd_Users_id` INT NOT NULL,
  `Da_Borrowing` DATE NOT NULL,
  `Da_Return` DATE NOT NULL,
  PRIMARY KEY (`Cd_id`, `Cd_Books_id`, `Cd_Users_id`),
  INDEX `fk_borroweds_books1_idx` (`Cd_Books_id` ASC),
  INDEX `fk_borroweds_users1_idx` (`Cd_Users_id` ASC),
  CONSTRAINT `fk_borroweds_books1`
    FOREIGN KEY (`Cd_Books_id`)
    REFERENCES `Library`.`D_Books` (`Cd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_borroweds_users1`
    FOREIGN KEY (`Cd_Users_id`)
    REFERENCES `Library`.`D_Users` (`Cd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library`.`F_Pendings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Library`.`F_Pendings` ;

CREATE TABLE IF NOT EXISTS `Library`.`F_Pendings` (
  `Cd_id` INT NOT NULL AUTO_INCREMENT,
  `Cd_Books_id` INT NOT NULL,
  `Cd_Users_id` INT NOT NULL,
  `Da_Request` DATE NOT NULL,
  PRIMARY KEY (`Cd_id`, `Cd_Books_id`, `Cd_Users_id`),
  INDEX `fk_pendings_books_idx` (`Cd_Books_id` ASC),
  INDEX `fk_pendings_users1_idx` (`Cd_Users_id` ASC),
  CONSTRAINT `fk_pendings_books`
    FOREIGN KEY (`Cd_Books_id`)
    REFERENCES `Library`.`D_Books` (`Cd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pendings_users1`
    FOREIGN KEY (`Cd_Users_id`)
    REFERENCES `Library`.`D_Users` (`Cd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
